### ISSUE TITLE
用gcloud 部署appid

### ISSUE THREAD

**Issue by Janet-Baker** [XX-net/XX-Net#13215]
遇到几个问题：
1.upload.bat里面写的是..\..\..\..\py27\2.0\python.exe ，可是那里放的是python3.8.2
改成系统安装过的py，再次执行，得到结果：

D:\Downloads\XX-Net\code\default\gae_proxy\server>python.exe uploader.py "coral-shift-266206" -debug
Traceback (most recent call last):
  File "uploader.py", line 48, in <module>
    from google.appengine.tools import appengine_rpc, appcfg
ModuleNotFoundError: No module named 'google'

装了gcloud sdk还不行啊……

**Comment by Janet-Baker** [comment]
测试了一下，app.yaml应该这么写：
主要就是修改了最前面的变量，去掉了不能写进去的东西。

```
runtime: python27
env: standard
threadsafe: true

handlers:
- url: /_gh/.*
  script: gae.application
  secure: optional

- url: /2
  script: wsgi.gae_application
  secure: optional

- url: /favicon.ico
  script: gae.application
  secure: optional

- url: /.*
  script: legacy.application
  secure: optional

libraries:
- name: pycrypto
  version: "latest"
```
