### ISSUE TITLE
gcloud部署指北（懒人精简版）

### ISSUE THREAD

**Issue by Janet-Baker** [XX-net/XX-Net#13218]
**精简版，需要一定的探索精神才能看的懂。**
**请一定按照自己的需求更改配置！**
**全程系统代理**

- 1.开权限。打开cloud build的权限，并将"App Engine"后面改成ENABLED

`https://console.cloud.google.com/cloud-build/settings/service-account`

- 2.下载gcloud sdk，自己安装。当然有解压版的，需要配置环境变量，自己搞去。

>  Windows安装版: [https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe](https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe)
>  免安装版[https://cloud.google.com/sdk/docs/downloads-versioned-archives](https://cloud.google.com/sdk/docs/downloads-versioned-archives)
>  其他:: [https://cloud.google.com/sdk/install](https://cloud.google.com/sdk/install)

- 3.初始化

打开命令提示符CMD，执行 `gcloud init` ，然后你会被要求登录、输入一大堆东西，包括项目名称、默认区域、用户体验改进计划……。区域默认7（us-central1便宜），当然你也可以试试44,45,46（香港），没有什么影响。一切随你，看着办就OK。

- 4.配置yaml文件

找到`XX-Net\code\default\gae_proxy\server\gae`，新建文本文档，命名为`app.yaml`，输入一下内容保存（不建议用记事本，可能会出一些莫名其妙的错误）
```
runtime: python27
env: standard
threadsafe: true

handlers:
- url: /_gh/.*
  script: gae.application
  secure: optional

- url: /2
  script: wsgi.gae_application
  secure: optional

- url: /favicon.ico
  script: gae.application
  secure: optional

- url: /.*
  script: legacy.application
  secure: optional

libraries:
- name: pycrypto
  version: "latest"

```

- 5.开始上传

回到命令提示符，输入`gcloud app deploy` ，打一个空格，然后把刚刚创建的yaml文件拖进去。看，是不是文件名带目录都进去了？

**警告：目录中尽量不要出现空格。如果出现，请自觉给带目录的文件名加引号**

然后，会联网校验，会询问确认上传，输入`Y`，回车。

如果担心确认时人不在，那就提前输入`Y`，回车。输入的时候可能会看不见，等到询问的时候，就会出现了。

等啊等，等上一小会，就搞定啦！

部署部分大概长这个样子：
```

Services to deploy:
descriptor:      [D:\Downloads\XX-Net\code\default\gae_proxy\server\gae\app.yaml]
source:          [D:\Downloads\XX-Net\code\default\gae_proxy\server\gae]
target project:  <项目名>
target service:  [default]
target version:  [年月日t时分秒]
target url:      [https://<项目名>.appspot.com]


Do you want to continue (Y/n)?  Y

Beginning deployment of service [default]...
#============================================================#
#= Uploading 4 files to Google Cloud Storage                =#
#============================================================#
File upload done.
Updating service [default]...done.
Setting traffic split for service [default]...done.
Deployed service [default] to [https://项目名.appspot.com]

You can stream logs from the command line by running:
  $ gcloud app logs tail -s default

To view your application in the web browser run:
  $ gcloud app browse
```

**大功告成！**
