### ISSUE TITLE
3.6.7其实很简单就能翻墙了

### ISSUE THREAD

**Issue by lyz440682** [XX-net/XX-Net#6860]
在data/gae_proxy/config.ini里加一句use_ipv6 = 1，然后重启XX-NET，软件里面自带了1万多个IPV6的IP，根本不需要搜索，又能重新YUTUBE了

**Comment by bubuchao** [comment]
试了一下，果然可以了

**Comment by PrinceAnna** [comment]
启用IPv6失败，请确认你的网络支持IPv6。
这就尴尬了

**Comment by SleeplessNights** [comment]
ipv4网络不行

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E7%B4%A2%E5%BC%95#isp%E5%B0%81%E9%94%81%E4%B8%A5%E9%87%8D%E6%90%9C%E4%B8%8D%E5%88%B0%E5%8F%AF%E7%94%A8ipv4

**Comment by lyz440682** [comment]
补充一下,我用联通和电信都能启动IPV6，不知道是不是因为我用的是WIN10系统

**Comment by SleeplessNights** [comment]
linux用户有点麻烦，有用arch设置ipv6成功的跟我说一下呀，削削

**Comment by vvvyyy** [comment]
你是用的校园网吧，前面帖子早说过了，用你来说？

**Comment by mtgitnerd** [comment]
怎么查看ipv6是否启用成功？

**Comment by lyz440682** [comment]
我自己家的是广电网络电视自带的宽带，应该是联通的宽带，我还试了下楼下的电信网络，都可以启动IPV6

**Comment by vvvyyy** [comment]
楼上有人说了，速度不行

**Comment by kevin1112222** [comment]
IP多了 但还是显示 尚未建立连接。。

**Comment by lyz440682** [comment]
我也不知道怎样才算速度不行，反正我能看1080p的YUTUBE，我家就10M的宽带

**Comment by vvvyyy** [comment]
应该不是每个人都可以开的，ipv6只有试点运营，再说打开也不用你那么麻烦，直接配置-高级设置里面就点开了，而且IP不是叫自带的，是ipv6的没被封

**Comment by nedved888** [comment]
win764，可以开，速度确实很慢。

**Comment by GraceLum** [comment]
请问加在哪一行? 对程序不熟悉

**Comment by jon945** [comment]
我虽然开启成功了，但是还是翻不过去，可能有的地区不行吧

**Comment by lyz440682** [comment]
前面那个大哥说的设置方式我是真没看见，我只能通过修改配置文件设置，我自己试了发现速度挺好，ip延迟只有300，我才介绍给大家，当然可能不是每个人都可以用IPV6，但是试试也无妨吧。

**Comment by ryu2gaku** [comment]
我 Mac 系统，`data/gae_proxy/config.ini` 路径下没有发现文件啊

倒是 `data/launcher/config.yaml` 路径有个 config 文件，内容如下

``` yaml
modules:
  gae_proxy: {auto_start: 1, show_detail: 1}
  launcher: {allow_remote_connect: 0, control_port: 8085, last_run_version: 3.6.7,
    proxy: pac, xxnet_port: 8087}
  x_tunnel: {auto_start: 1}
update: {last_path: /Users/ryugaku/Downloads/XX-Net-3.6.7/code/default/launcher, uuid: bed5e7ef-81ba-421c-b420-411beee2a704}
```
